# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 박지호
title: 백엔드 엔지니어
email: jiho5993@gmail.com
phone: 010-2382-5993
website: https://jiho5993.notion.site/f9fb3cb9721c4df093951e351a661c08

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: jiho5993
instagram_username: park_j2h5

# About Section
about_profile_image: images/pjh.jpg
about_content: |
  NodeJS, NestJS와 MySQL 기반의 서버 개발에 익숙하며,
  <mark>문서 분석과 실험을 통해 깊이 있게 기술을 탐구하는 것</mark>,
  그리고 <mark>장애 발생 시 상황을 재현하고 원인을 파악</mark>하는 것을 즐깁니다.<br>

  산업기능요원 복무 기간 동안 코인 입출금 서비스, 정산 시스템, 입출금 현황 대시보드 API 등 실무 중심의 백엔드 개발 경험을 쌓았습니다.
  특히, 웹소켓 통신으로 **약 3배의 성능 향상**과 MySQL 실행계획 분석을 통해, **2s -> 0.1ms로 데이터베이스 튜닝**을 이끌어냈습니다.<br>

  또한, **API Rate Limit 시스템을 구축**하여 유저별 API 호출 수를 제한하는 기능을 구현하였고,
  **모니터링 시스템 구축(Slack + Sentry), PNPM 모노레포 운영 경험**등이 있으며,
  항상 <mark>서비스 안정성</mark>과 <mark>확장성을 고민</mark>하는 개발자로 성장하고자 합니다.

content:
  - title: Experience
    layout: list
    content:
      - layout: top-middle
        title: 헥슬란트
        sub_title: Backend Engineer
        caption: 2022.10.31 - 2024.12.31
        # link: https://hexlant.com/ko
        quote: >
          블록체인 코인 입출금 서비스 구축 및 입출금 내역 대시보드 API 개발
        description: | # this will include new lines to allow paragraphs
          - 유저별 API Rate Limit 시스템 구축 (👉 [링크](https://jiho5993.notion.site/API-Rate-Limit-15f14d25e71c8082886dc09771c5d57d?pvs=4))
          - 웹 소켓을 활용한 RPC 통신 성능 개선 (👉 [링크](https://jiho5993.notion.site/Websocket-Helper-15714d25e71c80e1a6c2c00c6ebbca77?pvs=4))
            - <mark>약 150초 → 약 53초로 3배 개선</mark>
          - 코인 입출금 서비스 개발
          - 입출금 현황을 확인할 수 있는 대시보드 API 개발
          - 회계 / 세무 관련 정산 내역 발급 스케줄러 및 API 개발
          - 계약 시스템화 기능 개발
  - title: Project
    layout: list
    content:
      - layout: left
        title: WaggleWaggle
        caption: 2022.11 ~ 2023.12
        # link: 얜뭐지
        # link_text: 이건 뭐지
        additional_links:
          - title: 👉 API Github</br>
            icon: fab fa-github
            url: https://github.com/wagglewaggle/waggle-api
          - title: 👉 Scheduler Github</br>
            icon: fab fa-github
            url: https://github.com/wagglewaggle/waggle-population-scheduler
          - title: 👉 Entity Github
            icon: fab fa-github
            url: https://github.com/wagglewaggle/waggle-entity
        quote: >
          인구 혼잡도 제공 서비스
        description: | # this will include new lines to allow paragraphs
          - 서버 개발 전담
          - 혼잡도 API를 통해 일정 주기마다 혼잡도 정보를 가져와 DB에 저장하는 스케줄러 구현
          - Error Level을 두어 Normal일 경우와 Fatal일 경우에 대한 로직 분기
          - Sentry와 Slack을 도입하여 모니터링 시스템 구축
          - 한 요청 Lifecycle에서 반복적으로 사용되는 객체를 전역으로 관리하여 <mark>공통 로직을 줄이고 성능 개선</mark> (👉 [링크](https://jiho5993.notion.site/1a714d25e71c80fa8d8dfde59f6a79e4#1a814d25e71c80889f7bfbfa9e7f4228))
      - layout: left
        title: 영화 추천 챗봇 서비스
        caption: 2022.01 - 2022.06
        # link: 얜뭐지
        # link_text: 이건 뭐지
        additional_links:
          - title: 👉 API Github</br>
            icon: fab fa-github
            url: https://github.com/jiho5993/movchatbot/tree/main
        quote: >
          대학 졸업 작품으로 제작한 영화 추천 카카오 챗봇
        description: |
          - 서버 개발, 챗봇 시스템 구성
          - 카카오 챗봇과 REST API를 활용하여 영화 추천 서비스 제공
          - 크롤링을 병렬로 처리하여 성능 개선
            - <mark>약 5배의 비약적인 성능으로 개선 (12초 → 약 2초)</mark> (👉 [링크](https://jiho5993.notion.site/1a714d25e71c80fa8d8dfde59f6a79e4#1a914d25e71c80b9b608c0b278c135ab))
      - layout: left
        title: NerdIT
        caption: 2022.01 ~ 2022.10
        additional_links:
          - title: 👉 API Github</br>
            icon: fab fa-github
            url: https://github.com/DCPT-KNP/NerdIT-Backend
        quote: >
          디자이너들을 위한 자기개발 서비스
        description: |
          - 서버 개발 전담
          - 프론트엔드 개발자도 서버를 쉽게 실행할 수 있도록 Docker 스크립트 작성
          - 소셜 로그인 기능 구현
          - NestJS 프레임워크를 사용하여 API 서버 개발
            - <mark>Pipe</mark>, <mark>Guard</mark>, <mark>Filter</mark>등 NestJS의 다양한 기능을 활용
            - <mark>TypeORM</mark>을 사용하여 Repository 관리
          - Postman으로 API 문서화 (👉 [링크](https://documenter.getpostman.com/view/9352500/VUqpsxcG))
      - layout: left
        title: Gyumongeats
        caption: 2021.02 ~ 2021.06
        additional_links:
          - title: 👉 API Github</br>
            icon: fab fa-github
            url: https://github.com/jiho5993/gyumongeats
        quote: >
          쿠팡이츠 클론 프로젝트
        description: |
          - 서버 개발 전담
          - AWS Elastic Beanstalk을 활용하여 배포 (현재는 중단된 상태)
          - Sequelize ORM을 사용하여 DB 연동
      - layout: left
        title: 채팅 웹 어플리케이션
        caption: 2019.04 ~ 2019.06
        additional_links:
          - title: 👉 API Github</br>
            icon: fab fa-github
            url: https://github.com/jiho5993/open_source_chat_B-02
        quote: >
          웹소켓을 활용한 실시간 채팅 웹 어플리케이션
        description: |
          - ExpressJS와 SocketIO를 사용하여 웹소켓 서버 구현
          - Heroku를 활용하여 배포
  - title: Skills
    layout: list
    content:
      - layout: top-middle
        quote: >
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
      - layout: left
        title: Backend
        description: |
          - NodeJS, ExpressJS, NestJS
          - Typescript, Javascript
          - MySQL, Redis, TypeORM, Sequelize
          - NPM, Yarn Berry, PNPM
      - layout: left
        title: Tool
        description: |
          - Github, Git, GitKraken
          - Jira, Notion
          - ERDCloud, Postman
          - Visual Studio Code, Webstorm, DataGrip
          - Docker, Sentry, Slack
          - AWS EC2, AWS RDS, AWS S3
  - title: 대내외 활동
    layout: list
    content:
      - layout: left
        title: UMC 연합동아리
        sub_title: 스터디원(4기) & 운영진(5기)
        caption: 2023.03 - 2023.12
        description: |
          - 4기는 스터디원, 5기는 운영진으로 활동
          - 5기
            - 백엔드 파트 면접 준비
            - 운영진으로서 스터디원 관리 및 스터디 진행
      - layout: left
        title: 한양대학교 ERICA 원곡고등학교 코딩 교육 봉사
        sub_title: 스터디 멘토
        caption: 2019.09 - 2019.12
        description: |
          - C언어의 기초와 알고리즘을 알려주는 코딩 교육 봉사
          - 재귀함수에 대해 강의 진행
      - layout: left
        title: 한양대학교 ERICA C++ 알고리즘 스터디
        sub_title: 스터디 멘토
        caption: 2019.03 - 2019.06
        description: |
          - C++의 기초와 알고리즘을 알려주는 스터디
          - 기초 문법과 STL에 대해 강의 진행
  - title: Awards
    layout: list
    content:
      - layout: left
        title: SW창업아이디어톤 대상 (1위)
        sub_title: 한양대학교 ERICA
        caption: 2022.06.23 - 2022.06.24
      - layout: left
        title: HESH 해커톤 대상 (1위)
        sub_title: 한양대학교 ERICA
        caption: 2019.11.08 - 2019.11.10
      - layout: left
        title: HEPC 알고리즘 대회 우수상 (6위)
        sub_title: 한양대학교 ERICA
        caption: 2019.05.20
  - title: Education
    layout: list
    content:
      - layout: left
        title: 한양대학교 ERICA
        sub_title: 컴퓨터학부
        caption: 2018.03 - 2025.08 (졸업예정)
      - layout: left
        title: 유신고등학교
        caption: 2015.03 - 2018.02

# Footer
footer_show_references: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    'Gemfile',
    'Gemfile.lock',
    'node_modules',
    'vendor/bundle/',
    'vendor/cache/',
    'vendor/gems/',
    'vendor/ruby/',
    'lib/',
    'scripts/',
    'docker-compose.yml',
  ]
